import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-low':      '#f3f3f7',
        'surface-container-lowest':   '#ffffff',
        'surface-container-highest':  '#e2e2e6',
        'surface-container-high':     '#e7e8eb',
        'surface-container':          '#edeef1',
        'surface-dim':                '#d9dadd',
        'surface-bright':             '#f9f9fd',
        'surface-variant':            '#e2e2e6',
        'surface':                    '#f9f9fd',
        'on-surface':                 '#191c1e',
        'on-surface-variant':         '#424751',
        'on-background':              '#191c1e',
        'primary':                    '#00346f',
        'on-primary':                 '#ffffff',
        'primary-container':          '#004a99',
        'on-primary-container':       '#9bbdff',
        'primary-fixed':              '#d7e2ff',
        'primary-fixed-dim':          '#abc7ff',
        'on-primary-fixed':           '#001b3f',
        'on-primary-fixed-variant':   '#00458f',
        'inverse-primary':            '#abc7ff',
        'surface-tint':               '#255dad',
        'secondary':                  '#006a6a',
        'on-secondary':               '#ffffff',
        'secondary-container':        '#90efef',
        'on-secondary-container':     '#006e6e',
        'secondary-fixed':            '#93f2f2',
        'secondary-fixed-dim':        '#76d6d5',
        'on-secondary-fixed':         '#002020',
        'on-secondary-fixed-variant': '#004f4f',
        'tertiary':                   '#4d2f00',
        'on-tertiary':                '#ffffff',
        'tertiary-container':         '#6c4300',
        'on-tertiary-container':      '#ffab31',
        'tertiary-fixed':             '#ffddb8',
        'tertiary-fixed-dim':         '#ffb95f',
        'on-tertiary-fixed':          '#2a1700',
        'on-tertiary-fixed-variant':  '#653e00',
        'error':                      '#ba1a1a',
        'on-error':                   '#ffffff',
        'error-container':            '#ffdad6',
        'on-error-container':         '#93000a',
        'outline':                    '#737783',
        'outline-variant':            '#c2c6d3',
        'inverse-surface':            '#2e3133',
        'inverse-on-surface':         '#f0f0f4',
        'background':                 '#f9f9fd',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
        label:    ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
};

export default config;
